# Docker compose file for basic ngix ssl reverse proxy.

# Docker compose version
version: '3'

# Docker compose services.
services:

  # Docker reverse-proxy.
  reverse-proxy:
    # Configuration options that are applied at build time.
    image: nginx
    # Mount host paths or named volumes. 
    volumes:
     - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./conf/certificates:/etc/dlamp/certificates
    # Expose ports. 
    ports:
     - "80:80"
     - "443:443"
    # Link to containers in another service. 
    links:
      - web